config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products
  resources :cats
  resources :users
  post "users/:id" => "users#update"
  resources :carts
  post "carts/show" => "carts#update"
  get "orders/complete" => "orders#show"
  resources :orders

  get "logout", to: "sessions#destroy"

  get 'auth/:provider/callback', to: "sessions#omniauth_create"
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get 'homes/new'

end

app/models/cart.rb
class Cart < ApplicationRecord
  validates :quantity, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @cart = Cart.new
  end

  def show
    @product = Product.find(@cart.product_id)
    @cart = Cart.where(:user_id => session[:uid]).order("id desc").first
    # above line is equal to the below line.
    # @cart = Cart.where(:user_id => session[:uid]).last

  # If use product name, it's not unique id, so it cannot use as a display the product image.
  # When you use product name as a reference, you cannot display the image because of duplication of the product name.
    # names = @cart.product_name
    # @product = Product.find_by(:name => names)
  end

  def index
    @carts = Cart.where(:user_id => session[:uid]).all
    @total = 0
    # @images = []
    # @carts.each do |cart|
    #   names = cart.product_name
    #   product = Product.find_by(:name => names)
    #   @images.push(product.img_name)
    # end
  end

  def create
    @cart = Cart.new(carts_params)

    if session[:username].blank?
      redirect_to login_url
    else
      @cart.save
      if params[:buy_now]
        redirect_to("/orders/new")
      else
        redirect_to("/carts/show")
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.quantity = params[:quantity]
    @cart.save
    redirect_to("/carts/show")

    # @temp_cart = Cart.new(carts_params)
    # @cart = Cart.find_by(:id => @temp_cart.id)
    # @cart.destroy
    # @temp_cart.save
    # redirect_to("/carts/show")
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to("/carts/show")
  end

  def carts_params
    params.require(:cart).permit(:user_id, :product_id, :product_name, :price, :quantity, :total)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <table class="table bordered-table">
      <thead>
        <th></th>
        <th>Product Name</th>
        <th>Quantity</th>
        <th>Price(Rs)</th>
        <th>Subtotal(Rs)</th>
        <th></th>
      </thead>
      <tbody>
        <% @carts.each do |cart|
           product = Product.find(cart.product_id)
           @total += cart.total
        %>
        <tr>
          <td><%= image_tag(product.img_name, width:"100px", height:"100px") %></td>
          <td><%= cart.product_name %></td>
          <td><%= cart.quantity %></td>
          <td><%= cart.price %></td>
          <td><%= cart.total %></td>
          <td>
            <%= form_tag :url => { :controller => :carts, :action => :update } do %>
            <!-- if you write ':id' in the '_tag', rails automatically understand the value, so you don't need write ':value' -->
              <%= hidden_field_tag :id, cart.id %>
              <%= label_tag :quantity %>
              <%= select_tag :quantity, options_for_select(1..50, :selected => cart.quantity), :include_blank => false, style:"display:inline;" %>
              <%= submit_tag 'Change', class: "btn btn-success" %>
            <% end %>
            <%= link_to 'Delete', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", style:"margin-top:10px; margin-left:50px;" %>
          </td>
        </tr>
        <% end %>
        <tr>
          <td colspan="4"></td>
          <td> <span style="font-weight:bold;">total : Rs </span> <%= @total %> </td>
          <td><%= link_to 'Proceed to Check', new_order_path, class: "btn btn-primary", style:"color:white;" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
    <table class="table bordered-table">
      <thead>
        <th></th>
        <th>Product Name</th>
        <th>Quantity</th>
        <th>Price(Rs)</th>
        <th>Subtotal(Rs)</th>
        <th></th>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag(@product.img_name, width:"100px", height:"100px") %></td>
          <td><%= @cart.product_name %></td>
          <td><%= @cart.quantity %></td>
          <td><%= @cart.price %></td>
          <td><%= @cart.total %></td>
          <td>
            <%= form_tag :url => { :controller => :carts, :action => :update } do %>
            <!-- if you write ':id' in the '_tag', rails automatically understand the value, so you don't need write ':value' -->
              <%= hidden_field_tag :id, @cart.id %>
              <%= label_tag :quantity %>
              <%= select_tag :quantity, options_for_select(1..50, :selected => @cart.quantity), :include_blank => false, style:"display:inline;" %>
              <%= submit_tag 'Change', class: "btn btn-success" %>
            <% end %>
            <%= link_to 'Delete', @cart,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "btn btn-warning",
                        style:"margin-top:10px; margin-left:50px;" %>
          </td>
        </tr>
        <tr>
          <td colspan="4"></td>
          <td><%= link_to 'Back', product_path(@product.id), class: "btn btn-default btn-block" %></td>
          <td><%= link_to 'Go to Your Cart', carts_path, class: "btn btn-primary", style:"color:white;" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>