config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products
  resources :cats
  resources :users
  post "users/:id" => "users#update"
  resources :carts
  post "carts/show" => "carts#update"
  get "orders/complete" => "orders#show"
  resources :orders

  get "logout", to: "sessions#destroy"

  get 'auth/:provider/callback', to: "sessions#omniauth_create"
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get 'homes/new'

end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # skip_before_action :authorize
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    @admin = User.find_by(id: 2)
    @cats = Cat.all
    @cat = Cat.find_by(id: params[:id])
    @products = Product.where(:category_id => @cat.category_name).all
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:category_name)
    end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_with(model: cat, local: true) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name, id: :cat_category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cats</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.category_name %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<div class="row header-image">
  <div class="col-md-12">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval=10000>
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "mv_1.jpg", class: "image" %>
        </div>
        <div class="item">
          <%= image_tag "mv_2.jpg", class: "image" %>
        </div>
      </div>
      <!-- Left and right controls -->
      <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a> -->
    </div>
  </div>
</div>

<div class="container-fluid content">
  <div class="row menu">
    <div class="col-md-12">
      <ul>
        <li>
          <%= link_to "ALL", root_path %>
        </li>
        <% @cats.each do |cat| %>
        <li class="category-menu">
          <%= link_to(cat.category_name, "/cats/#{cat.id}") %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row items-wrapper">
    <ul>
      <% @products.each do |product| %>
      <li class="item col-xs-6 col-sm-3 col-md-2">
        <%= link_to image_tag(product.img_name, :class => "item-image"), :controller => 'products', :action => 'show', :id => product.id %>
        <div class="item-detail">
          <div class="item-name">
            <%= product.name %>
          </div>
          <div class="item-price">
            Rs<%= product.price %>
          </div>
          <div class="item-category">
            #<%= product.category_id %>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<% if @admin.password_digest == session[:password] %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Category name:</strong>
    <%= @cat.category_name %>
  </p>

  <%= link_to 'Edit', edit_cat_path(@cat) %> |
  <%= link_to 'Back', cats_path %>
<% end %>