config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products
  resources :cats
  resources :users
  post "users/:id" => "users#update"
  resources :carts
  post "carts/show" => "carts#update"
  get "orders/complete" => "orders#show"
  resources :orders

  get "logout", to: "sessions#destroy"

  get 'auth/:provider/callback', to: "sessions#omniauth_create"
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get 'homes/new'

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :img_name, ImageUploader
  validates :quantity, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authorize, only: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :js, :json, :html

  # GET /products
  # GET /products.json
  def index
    @user = User.new
    @products = Product.all
    @cats = Cat.all
    @temps = Product.where(category_id: params[:id])
    if @temps.blank?
      respond_to do |format|
        format.html
        format.json { render json: @products }
      end
    else
      respond_to do |format|
        format.html
        format.json { render json: @temps }
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @products = Product.where(:category_id => @product.category_id).all

    @user = User.new
    @admin = User.find_by(id: 2)
    @cart = Cart.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :category_id, :img_name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, multipart: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(Cat.all, :category_name, :category_name) %>
  </div>

  <div class="field">
    <%= form.label :img_name %>
    <%= form.file_field :img_name, id: :product_img_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row header-image">
  <div class="col-md-12">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval=10000>
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "mv_1.jpg", class: "image" %>
        </div>
        <div class="item">
          <%= image_tag "mv_2.jpg", class: "image" %>
        </div>
      </div>
      <!-- Left and right controls -->
      <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a> -->
    </div>
  </div>
</div>

<div class="container-fluid content">
  <div class="row menu">
    <div class="col-md-12">
      <ul>
        <li id="all">
          All
        </li>
        <% @cats.each do |cat| %>
        <li class="category-menu" id="<%= cat.category_name %>">
          <%= cat.category_name %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row items-wrapper" style="margin-bottom:20px;">
    <!-- this is created by ajax dynamically -->
  </div>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 item-image">
      <%= image_tag(@product.img_name, width: "400px", height: "400px", class: "item-img") %>
    </div>
    <div class="col-md-6 item-detail">
      <div class="category">
        <p>#<%= @product.category_id %></p>
      </div>
      <h1><%= @product.name %></h1>
      <div class="price">
        <h4>Rs<%= @product.price %></h4>
      </div>
      <%= form_for @cart, :url => { :controller => :carts, :action => :create } do |cart| %>
        <div class="hidden-field">
          <%= cart.hidden_field :user_id, value: session[:uid] %>
          <%= cart.hidden_field :product_id, value: @product.id %>
          <%= cart.hidden_field :product_name, value: @product.name %>
          <%= cart.hidden_field :price, value: @product.price %>
          <%= cart.hidden_field :total, value: @product.price, id: "total" %>
        </div>
        <div class="form-group" style="padding-top: 10px;">
          <%= cart.label :quantity, class: "form-control", style: "display:inline; background-color:orange; color:white; font-family:sans-serif;" %>
          <!-- below line create automatically id="cart_quantity" -->
          <%= cart.select :quantity, (1..50), :include_blank => false, class: "form-control" %>

          <script>
          $(document).ready(function(){
            $('[id = cart_quantity]').change(function(){
              var amount = $('[id = cart_quantity] option:selected').text();
              // if argument is string or varchar, you should use beloe function.
              // Number(amount);
              var price = <%= @product.price %>;
              var subTotal = amount * price;
              $('#subtotal').html(subTotal);
              $('#total').val(subTotal);
            });
          });
          </script>

          Sub total:<div id="subtotal" style="display: inline;"></div>
        </div>
        <div class="action">
          <%= cart.submit("Add to Cart", class: "btn btn-warning btn-block", style: "margin-top: 20px;") %>
        </div>
        <div class="action">
          <%= cart.submit("Buy Now", class: "btn btn-success btn-block", style: "margin-top: 20px;", name: "buy_now") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default" style="margin-top:20px;">
        <div class="panel-heading">
          <h4>Recommended for you</h4>
        </div>
        <div class="panel-body">
          <ul>
            <% @products.each do |product| %>
              <li style="float:left; margin-right:10px; margin-right:10px;">
                <div class="panel-image" style="display: inline;">
                  <%= link_to image_tag(product.img_name, width:"100px", height:"100px"), :controller => 'products', :action => 'show', :id => product.id %>
                  <!-- <%= link_to image_tag(product.img_name, width:"100px", height:"100px") %> -->
                </div>
              </li>
              <li style="float:left; margin-right:10px;">
                <div class="panel-detail" style="display: inline;">
                  <p><%= product.name %></p>
                  <p>Rs<%= product.price %></span>
                  <p>#<%= product.category_id %></p>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <% if @admin.password_digest == session[:password] %>
  <div class="manage-product">
    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @product.price %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @product.category_id %>
    </p>

    <p>
      <strong>Img name:</strong>
      <%= @product.img_name %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', products_path %>
  </div>
  <% end %>

</div>