config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products
  resources :cats
  resources :users
  post "users/:id" => "users#update"
  resources :carts
  post "carts/show" => "carts#update"
  get "orders/complete" => "orders#show"
  resources :orders

  get "logout", to: "sessions#destroy"

  get 'auth/:provider/callback', to: "sessions#omniauth_create"
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get 'homes/new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  validates :quantity, presence: true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :img_name, ImageUploader
  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_secure_password(validations: false)
    validates :username, presence: true
    validates :password, presence: true, length: {minimum: 4}, allow_nil: true
    validates :email, presence: false, uniqueness: true
    # validates :date_of_birth, presence: true
    # validates :image, presence: true

  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      username: auth['info']['name'],
      email: auth['info']['email'],
      image: auth['info']['image'],
      provider: auth['provider'],
      uid: auth['uid']
    )
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @cart = Cart.new
  end

  def show
    @product = Product.find(@cart.product_id)
    @cart = Cart.where(:user_id => session[:uid]).order("id desc").first
    # above line is equal to the below line.
    # @cart = Cart.where(:user_id => session[:uid]).last

  # If use product name, it's not unique id, so it cannot use as a display the product image.
  # When you use product name as a reference, you cannot display the image because of duplication of the product name.
    # names = @cart.product_name
    # @product = Product.find_by(:name => names)
  end

  def index
    @carts = Cart.where(:user_id => session[:uid]).all
    @total = 0
    # @images = []
    # @carts.each do |cart|
    #   names = cart.product_name
    #   product = Product.find_by(:name => names)
    #   @images.push(product.img_name)
    # end
  end

  def create
    @cart = Cart.new(carts_params)

    if session[:username].blank?
      redirect_to login_url
    else
      @cart.save
      if params[:buy_now]
        redirect_to("/orders/new")
      else
        redirect_to("/carts/show")
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.quantity = params[:quantity]
    @cart.save
    redirect_to("/carts/show")

    # @temp_cart = Cart.new(carts_params)
    # @cart = Cart.find_by(:id => @temp_cart.id)
    # @cart.destroy
    # @temp_cart.save
    # redirect_to("/carts/show")
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to("/carts/show")
  end

  def carts_params
    params.require(:cart).permit(:user_id, :product_id, :product_name, :price, :quantity, :total)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # skip_before_action :authorize
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    @admin = User.find_by(id: 2)
    @cats = Cat.all
    @cat = Cat.find_by(id: params[:id])
    @products = Product.where(:category_id => @cat.category_name).all
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:category_name)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  def home

  end

  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # file = params[:user][:image]
    # if !file.nil?
    #   file_name = file.original_filename
    #   File.open("public/user_images/#{file_name}", 'wb')
    #     {|f| f.write(file.read)}
    #   @user.image = file_name
    # end
    if @user.save
      flash[:notice] = "Created your account !"
      redirect_to login_path
    else
      render("/users/new")
    end
  end

  def update
    @user = User.find(params[:id])
    # @user.username = params[:username]
    # @user.password = params[:password]
    # @user.email = params[:email]
    # @user.phone = params[:phone]
    # @user.image = params[:image]
    if @user.save(user_params)
      session[:username] = @user.username
      session[:password] = @user.password_digest
      session[:image] = @user.image.url
      flash[:notice] = "Update successfully !"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Account deleted! Thank you using this site!"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :phone, :gender, :date_of_birth, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    # session[] is global variable.
    session[:uid] = user.id
    session[:username] = user.username
    session[:password] = user.password_digest
    session[:image] = user.image.url
  end

  def log_out
    session.delete(:uid)
    session.delete(:username)
    session.delete(:password)
    session.delete(:image)
    session.delete(:omniauth)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
    <div class="container-fluid footer">
      <div class="row">
        <p>Copyright © MISAO Co.,ltd. All Rights Reserved.</p>
      </div>
    </div>

  </body>
</html>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BEST INDIA.com</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->


  </head>
  <body>

app/views/layouts/_header.html.erb
<nav class="navbar header" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar" style="color:balck;"></span>
        <span class="icon-bar" style="color:balck;"></span>
        <span class="icon-bar" style="color:balck;"></span>
      </button>
      <div class="navbar-brand navbar-brand-centered">
        <%= link_to image_tag("logo.png"), root_path, class: "logo-image", style: "background-color:white; cursor:pointer;" %>
      </div>
    </div>
  </div>

  <div class="collapse navbar-collapse" id="bs-navbar-collapse">
    <div class="row header-menu">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a href="/" id="header-all">
            <span class="glyphicon glyphicon-home" aria-hidden="false"></span> <br>
            HOME
          </a>
        </li>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" id="nav_item" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-search" aria-hidden="false"></span> <br>
            ITEM
          </a>
          <ul class="dropdown-menu">
            <% Cat.all.each do |cat| %>
            <li class="category-menu" id="<%= cat.category_name %>"> <%= cat.category_name %> </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="visible-xs">
        <li>
          <a href="/">HOME</a>
        </li>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" id="nav_item" aria-haspopup="true" aria-expanded="false">
            ITEM
          </a>
        </li>
      </ul>

    <!-- <div class="col-md-4 logo">
      <%= link_to image_tag("logo.png"), root_path, class: "logo-image navbar-brand" %>
    </div> -->
      <ul class="nav navbar-nav navbar-right">
        <!-- login button and register button display or not -->
        <% if session[:username].blank? %>
          <li>
            <div class="btn btn-default" id="login-button">
              <span class="glyphicon glyphicon-user" aria-hidden="false"></span> <br>
              <span style="font-family: fantasy;">LOGIN</span>
            </div>
          </li>
          <li>
            <div class="btn btn-default" id="register-button">
              <span class="glyphicon glyphicon-info-sign" aria-hidden="false"></span> <br>
              <span style="font-family: fantasy;">REGISTER</span>
            </div>
          </li>
          <li>
            <div class="">
              <a href="/login">
                <div class="btn btn-default">
                  <span class="glyphicon glyphicon-shopping-cart" style="pointer-events: none; text-decoration: none;" aria-hidden="false"></span> <br>
                  <span style="font-family: fantasy; pointer-events: none;">CART</span>
                  <span style="font-family: fantasy;"> 0 </span>
                </div>
              </a>
            </div>
          </li>
          <% else %>
          <li>
            <div class="">
              <a href="/users/<%=session[:uid]%>" style="text-decoration: none;">
                <div class="btn btn-default">
                  <%= image_tag(session[:image], width: "40px", height: "40px", style: "pointer-events:none;") %> <br>
                  <span style="font-family: fantasy;"><%= session[:username] %></span>
                </div>
              </a>
            </div>
          </li>
          <li>
              <!-- <a href="/logout" style="text-decoration: none;"> -->
              <div class="">
                <%= link_to logout_path do %>
                  <div class="btn btn-default">
                    <span class="glyphicon glyphicon-user" aria-hidden="false"></span> <br>
                    <span style="font-family: fantasy;">LOGOUT</span>
                  </div>
                <% end %>
              </div>
              <!-- </a> -->
          </li>
          <li>
            <div class="">
              <%= link_to carts_path do %>
                <div class="btn btn-default">
                  <span class="glyphicon glyphicon-shopping-cart" style="pointer-events: none; text-decoration: none;" aria-hidden="false"></span> <br>
                  <span style="font-family: fantasy; pointer-events: none;">CART</span>
                  <span style="font-family: fantasy; pointer-events: none;">
                    <%= Cart.where(:user_id => session[:uid]).all.count %>
                  </span>
                </div>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
      <ul class="visible-xs">
        <% if session[:username].blank? %>
          <li><a href="/login">LOGIN</a></li>
          <li><a href="/users/new"></a>REGISTER</li>
          <li><a href="/login"></a>CART</li>
        <% else %>
          <li>
            <a href="/users/<%=session[:uid]%>">GO TO <%= session[:username] %> PAGE</a>
          </li>
          <li><a href="/logout">LOGOUT</a></li>
          <li>
            <a href="/carts/show">CART</a><%= Cart.where(:user_id => session[:uid]).all.count %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>

  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>

</nav>

  <div id="modal-overlay"></div>
  <%= render partial: 'layouts/login_modal' %>

  <% if session[:uid].blank? %>
    <%= render partial: 'layouts/register_modal' %>
  <% end %>

</div>

app/views/layouts/_login_form.html.erb
<h3>WELCOME</h3>
<%= render partial: "layouts/providers" %>

<hr>

<h3>LOGIN</h3>
<div class="form-group">
  <%= form_tag({ :controller => :sessions, :action => :create }) do %>
    <%= label_tag :username %>
    <%= text_field_tag :username, params[:username], placeholder: "Enter username", class: "form-control" %> <br>
    <%= label_tag :password %>
    <%= password_field_tag :password, params[:password], placeholder: "Enter password", class: "form-control" %> <br>
    <%= submit_tag "Submit", class: "btn btn-warning btn-block" %> <br>
    Not member? <br>
  <% end %>
</div>

app/views/layouts/_login_modal.html.erb
<div class="container" id="login-modal">
  <div class="row">
    <div class="col-md-12">
      <%= render partial: "layouts/login_form" %>
      <div id="create-btn" class="btn btn-primary btn-block">
        Create your Account
      </div>
    </div>
  </div>
</div>

app/views/layouts/_providers.html.erb
<div class="buttons">
  <ul>
    <li>
      <%= link_to "auth/facebook" do %>
        <div class="btn btn-default btn-facebook">
          <span class="fa fa-facebook"></span>
          Facebook
        </div>
      <% end %>
    </li>
    <li>
      <%= link_to "auth/twitter" do %>
        <div class="btn btn-default btn-twitter">
          <span class="fa fa-twitter"></span>
          Twitter
        </div>
      <% end %>
    </li>
    <li>
      <%= link_to "auth/google_oauth2" do %>
        <div class="btn btn-default btn-google">
          <span class="fa fa-google"></span>
          Google
        </div>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/_register_form.html.erb
<h3>REGISTER</h3>
<%= render partial: "layouts/providers" %>

<hr>

<h3>Enter your information</h3>
<div class="form-group">
  <!-- !caution! rails automatically recognize @user is to send 'users_controller.rb'.
      when you use different name's controller, an error message 'uninitialized constant UsersController' will be displayed.
      you can choose 2 options to avoid this problem.
      1. create same name's controller(users_controller.rb) to use @user
      2. add options which controller you want to use, and in the controller, which method you want to use... or something -->
  <%= form_for(@user, multipart: true) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control", placeholder: "Enter your name" %> <br>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %> <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter the same password" %> <br>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "Enter your email" %> <br>
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control", placeholder: "Enter your phone number" %> <br>
    <%= f.label :gender %>
    <%= f.radio_button :gender, "Male" %>Male
    <%= f.radio_button :gender, "Female" %>Female <br><br>
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth, { :include_blank => false, :start_year => 1900 }, { class: "form-control bootstrap-date" } %> <br>
    <%= f.label :image %>
    <span class="btn btn-warning btn-file" style="margin-bottom: 20px;">
      Choose File
      <%= f.file_field :image, class: "form-control" %>
    </span> <br>
    <%= f.submit "Create", class: "btn btn-primary btn-block" %> <br>
  <% end %>
</div>

app/views/layouts/_register_modal.html.erb
<div class="container" id="register-modal">
  <div class="row">
    <div class="col-md-12">
      <%= render partial: "layouts/register_form" %>
      <hr>
      <span id="login-link" style="color:blue; cursor:pointer;">
        You already have an account?
      </span>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<%= render partial: 'layouts/head' %>
<%= render partial: 'layouts/header' %>

  <%= yield %>

  </div>

<%= render partial: '/layouts/footer' %>